\ExplSyntaxOn

\input{coverinfo.sty}
\input{profile/packages.sty}
\input{profile/font.sty}
\input{profile/cover.sty}
\input{profile/abstract.sty}
\input{profile/page.sty}
\input{profile/components.sty}

% ctex格式设置
\ctexset{
    contentsname = \songti\bfseries\zihao{3}目录,
    chapter/format = \zihao{4}\bfseries\centering,
    section/format = \zihao{4}\bfseries\raggedright,
    subsection/format = \zihao{4}\bfseries\raggedright,
    subsubsection/format = \zihao{4}\bfseries\raggedright
}

\ExplSyntaxOff